#!/usr/bin/env python3
from liblo import *
import sys

print ("=============================================")
print ("============ ESP32 - MONITOR ================")
print ("=============================================")
print ("")

# raw_input renamed to input in python3
try:
    input = raw_input
except NameError:
    pass

class MyServer(ServerThread):
    def __init__(self):
        ServerThread.__init__(self, 1819)

    @make_method('/status', 'iidssiFiTss')
    def foo_callback(self, path, args):
        print(path, args)

    @make_method(None, None)
    def fallback(self, path, args):
        print("received unknown message '%s'" % path)

try:
    server = MyServer()
except ServerError as err:
    print(err)
    sys.exit()

server.start()
input("press enter to quit...\n")






while True:
    time.sleep(1)